config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  namespace :account do
   resources :orders
   resources :appointments do
     member do
       post :apply_to_cancel
     end
   end
 end

  namespace :admin do
    resources :products
    resources :services
    resources :categories
    resources :blogs
    resources :topics
    resources :appointments do
      member do
        post :deal
        post :confirm
        post :cancel
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
    resources :reviews
  end

  resources :services do
    resources :comments
    resources :appointments
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders
  resources :blogs do
    member do
      put "like", to: "blogs#upvote"
      put "dislike", to: "blogs#downvote"
    end
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :booking_name, presence: true
  validates :booking_phone, presence: true
  validates :booking_time, presence:true
  validates :booking_email, presence:true

  def book!
    self.update_columns(is_booked: true)
  end


  include AASM
  aasm do
    state :order_placed, initial: true
    state :booked
    state :confirming
    state :confirmed
    state :appointment_cancelled

    event :make_appointment, after_commit: :book! do
      transitions from: :order_placed, to: :booked
    end

    event :deal do
      transitions from: :booked,  to: :confirming
    end

    event :confirm do
      transitions from: :confirming, to: :confirmed
    end

    event :cancel_appointment do
      transitions from: [:booked, :confirming, :confirmed], to: :appointment_cancelled
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

	mount_uploader :image, ImageUploader
	belongs_to :user
	belongs_to :topic
	has_many :messages

	scope :recent, -> { order("created_at DESC")}

  acts_as_votable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
   cart_items.destroy_all
 end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :body, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :blog
	validates :body, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  belongs_to :user

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  has_many :product_lists

  
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :reviews
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :body, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :appointments
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :blogs

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
    is_admin
  end

  has_many :orders
  has_many :comments
  has_many :reviews

  has_many :blogs
  has_many :messages
  
  has_many :appointments

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
      @service = Service.new(service_params)

      if @service.save
          redirect_to admin_services_path
      else
          render :new
      end
  end

  def edit
      @service = Service.find(params[:id])
  end

  def update
      @service = Service.find(params[:id])

      if @service.update(service_params)
          redirect_to admin_services_path
      else
          render :edit
      end
  end



  private
  def service_params
    params.require(:service).permit(:title, :price, :description, :image)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def index
        @services = Service.all
     end

    def show
        @service = Service.find(params[:id])
        @appointment = Appointment.new
    end
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/services/edit.html.erb
<h2> Edit Service </h2>

<%= simple_form_for [:admin, @service] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>


  <div class="group">
    <%= f.input :price %>
  </div>

  <% if @service.image.present? %>
   <span>目前商品图</span> <br>
   <%= image_tag(@service.image.thumb.url) %>
 <% end %>

 <div class="group">
   <%= f.input :image, as: :file %>
 </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/services/index.html.erb
<h2 class="text-center"> Service List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增服务", new_admin_service_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Price</th>
      <th width="200">Description</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td>
          <%= service.id %>
        </td>

        <td>
          <%= service.title %>
        </td>
        <td>
          <%= service.price %>
        </td>
        <td>
          <%= service.description %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_service_path(service)) %> |
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/services/new.html.erb
<h2> New Service </h2>

<%= simple_form_for [:admin, @service] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>


  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
   <%= f.input :image, as: :file %>
 </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/services/index.html.erb
<div class="row service-nav">
    <div class="col-sm-2 col-sm-offset-2">
        <h4>Service</h4>
    </div>
    <div class="col-sm-2 col-sm-offset-5 text-center">
        <h5 class="home_link"> <%= link_to("Home", root_path, :style => 'color: #f4ad53;') %>  > service</h5>
    </div>
</div>

<div class="row service">
    <div class="text-center">
        <h2>Our Service</h2>
        <p>
            <img src="https://ww3.sinaimg.cn/large/006y8lVagy1fcnzbl4t11j306w00fgld.jpg" alt="crow">
        </p>
    </div>
    <br>

    <div>

        <div class="col-sm-3 col-sm-offset-1">
            <ul class="list-unstyled">
                <li class="full-grooming">
                    <h4 class="pull-right"><%= link_to("Full Grooming", service_path(1)) %>
                        <span class="icon"><img src="https://ww4.sinaimg.cn/large/006tNbRwgy1fcokzx4gatj302q02smx1.jpg" alt="icon-scissors"></span>
                    </h4>

                    <p class="pull-right">Your pet is in good hands with us! Let your favorite get the best care in our center.</p>
                </li>
                <li class="bath">
                    <h4 class="pull-right"><%= link_to("Bath & Dry", service_path(2)) %>
                        <span class="icon"><img src="https://ww2.sinaimg.cn/large/006tNbRwgy1fcol1xnb5ej302s02sjr9.jpg" alt="icon-bath"></span>
                    </h4>
                    <p class="pull-right">We use a big range of shampoos for all different coat types and breeds</p>
                </li>
            </ul>
        </div>


        <div class="col-sm-4 text-center">
            <img src="https://ww1.sinaimg.cn/large/006tNbRwgy1fcok7uawv8j308z0chtb7.jpg" alt="pet1">
        </div>

        <div class="col-sm-3">
            <ul class="list-unstyled">
                <li class="styling">
                    <h4 class="pull-left">
                        <span class="icon"><img src="https://ww4.sinaimg.cn/large/006tNbRwgy1fcol5oimuwj302s02smx1.jpg" alt="icon-styling"></span><%= link_to("Styling", service_path(3)) %>
                    </h4>
                    <p class="pull-left">Our team of pet hair stylists is happy to make your animal look pretty and happy.
                    </p>
                </li>
                <li class="medical">
                    <h4 class="pull-left">
                        <span class="icon"><img src="https://ww2.sinaimg.cn/large/006tNbRwgy1fcol9fjfeqj302s02s0sl.jpg" alt="icon-medical"></span><%= link_to("Medical Bath", service_path(4)) %></h4>
                    <p class="pull-left">Bathing in our vet bath, using an appropriate shampoo that is kind to pet’s skin.</p>
                </li>
            </ul>
        </div>

    </div>

</div>

<div class="row bg1">
    <div class="col-sm-12">
        <img src="https://ww1.sinaimg.cn/large/006tNbRwgy1fcomaf6s7pj31hc0eq44h.jpg" alt="bg1" width="100%">
    </div>
</div>

<div class="row package">
    <div class="text-center">
        <h2>Our Packages</h2>
        <p style="margin-bottom: 0px;">
            <img src="https://ww3.sinaimg.cn/large/006y8lVagy1fcnzbl4t11j306w00fgld.jpg" alt="crow">
        </p>
    </div>

    <div class="row package">
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <img class="img-circle" width="134" height="134" alt="image1" src="http://pets-grooming.axiomthemes.com/wp-content/uploads/2016/07/image-22-156x156.jpg">
                </div>
                <div class="panel-body">
                    <h3>Deluxe Bath &amp; Groom</h3>

                    <p>Grooming service for a small dog </p>
                      <p>include bathing</p>
                      <p> ear cleaning and grooming.</p>
                </div>
                <div class="panel-footer">
                    <h3>$54</h3>
                    <button class="btn btn-lg">Enquire now</button>
                </div>
            </div>
        </div>

        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <img class="img-circle" width="134" height="134" alt="image1" src="http://pets-grooming.axiomthemes.com/wp-content/uploads/2016/07/price2-156x156.jpg">
                </div>
                <div class="panel-body">
                    <h3>Bath & Full Groom</h3>

                    <p>Our full groom package </p>
                    <p>  includes: bath </p>
                      <p>dry with styling and nail clipping.</p>
                </div>
                <div class="panel-footer">
                    <h3>$69</h3>
                    <button class="btn btn-lg">Enquire now</button>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-xs-12">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <img class="img-circle" width="134" height="134" alt="image1" src="http://pets-grooming.axiomthemes.com/wp-content/uploads/2016/07/price3-156x156.jpg">
                  </div>
                <div class="panel-body">
                    <h3>Bath & Tidy Up</h3>

                    <p>Our service for a large dog </p>
                      <p>include nail trim</p>
                        <p> cleaning, haircut and blow dry. </p>
                </div>
                <div class="panel-footer">
                    <h3>$63</h3>
                    <button class="btn btn-lg">Enquire now</button>
                </div>
            </div>
        </div>


</div>

app/views/services/show.html.erb
<div class="service-sidebar">
    <div class="row">
        <div class="col-sm-2">
            <h4 class="text-center">Services List</h4>
        </div>
        <div class="col-sm-2 col-sm-offset-2">
            <p>
                <span class="fa fa-caret-right"></span>
                Full Grooming</p>
        </div>
        <div class="col-sm-2">
            <p>
                <span class="fa fa-caret-right"></span>
                Bath & Dry</p>
        </div>
        <div class="col-sm-2">

            <p>
                <span class="fa fa-caret-right"></span>
                Styling</p>
        </div>
        <div class="col-sm-2">
            <p>
                <span class="fa fa-caret-right"></span>
                Medical Bath</p>
        </div>
    </div>
</div>

<div class="row" style=" margin-top: 50px;">
    <div class="col-sm-8 col-sm-offset-3">
        <div class="service-image">
            <% if @service.image.present? %>
            <%= image_tag(@service.image.url, class: "thumbnail") %>
        <% else %>
            <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
            <% end %>
        </div>
    </div>

</div>

<div class="row content">
    <div class="col-sm-8 col-sm-offset-1">
        <h4><%= @service.title %></h4>
        <p><%= simple_format(@service.description) %></p>
    </div>
    <div class="col-sm-11">
        <div class="pull-right" style="margin-top: 60px;">
            <a href="#" data-toggle="modal" data-target="#appointment" class="btn btn-lg">Make an Appointment</a>
            <div class="modal fade" id="appointment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                <div class="modal-dialog" role="document">
                    <div class="loginmodal-container">
                        <%= simple_form_for [@service, @appointment] do |f| %>
                        <%= f.error_notification %>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="text-center">Booking Application</h4>
                        <div class="form-inputs">
                            <%= f.input :booking_name%>
                            <%= f.input :booking_phone %>
                            <%= f.input :booking_email %>
                            <%= f.input :booking_time , as: :date %>
                          </div>
                            <div class="form-actions">
                                <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
                            </div>
                            <% end %>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row comment">
        <div class="col-sm-10 col-sm-offset-1">
            <h3 class="comments_title">
                <%= @service.comments.count %>
                Comments
            </h3>
            <hr>
            <div id="comments">
                <%= render @service.comments%>
                <hr>
                <%= render "comments/form"%>
            </div>
        </div>
    </div>

    <!-- 以下代码为预约弹窗代码 -->