config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  namespace :account do
   resources :orders
   resources :appointments do
     member do
       post :apply_to_cancel
     end
   end
 end

  namespace :admin do
    resources :products
    resources :services
    resources :categories
    resources :blogs
    resources :topics
    resources :appointments do
      member do
        post :deal
        post :confirm
        post :cancel
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
    resources :reviews
  end

  resources :services do
    resources :comments
    resources :appointments
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders
  resources :blogs do
    member do
      put "like", to: "blogs#upvote"
      put "dislike", to: "blogs#downvote"
    end
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :booking_name, presence: true
  validates :booking_phone, presence: true
  validates :booking_time, presence:true
  validates :booking_email, presence:true

  def book!
    self.update_columns(is_booked: true)
  end


  include AASM
  aasm do
    state :order_placed, initial: true
    state :booked
    state :confirming
    state :confirmed
    state :appointment_cancelled

    event :make_appointment, after_commit: :book! do
      transitions from: :order_placed, to: :booked
    end

    event :deal do
      transitions from: :booked,  to: :confirming
    end

    event :confirm do
      transitions from: :confirming, to: :confirmed
    end

    event :cancel_appointment do
      transitions from: [:booked, :confirming, :confirmed], to: :appointment_cancelled
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

	mount_uploader :image, ImageUploader
	belongs_to :user
	belongs_to :topic
	has_many :messages

	scope :recent, -> { order("created_at DESC")}

  acts_as_votable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
   cart_items.destroy_all
 end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :body, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :blog
	validates :body, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  belongs_to :user

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  has_many :product_lists

  
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :reviews
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :body, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :appointments
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :blogs

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
    is_admin
  end

  has_many :orders
  has_many :comments
  has_many :reviews

  has_many :blogs
  has_many :messages
  
  has_many :appointments

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
   current_cart.clean!
   flash[:warning] = "Deleted All"
   redirect_to carts_path
 end

 def checkout
   @order = Order.new
 end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/checkout.html.erb
<div class="row">
   <div class="col-md-12">

    <h2> 购物明细 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明细</th>
          <th>单价</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>

            <td>
              <%= cart_item.quantity %>
            </td>

          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计 <%= render_cart_total_price(current_cart) %> CNY
      </span>
    </div>

    <hr>

    <h2> 订单资讯 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>



          <legend> 订购人</legend>
          <div class="form-group col-lg-6">
            <%= f.input :billing_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= f.input :billing_address  %>
          </div>

          <legend> 收货人</legend>
          <div class="form-group col-lg-6">
           <%= f.input :shipping_name  %>
          </div>
          <div class="form-group col-lg-6">
            <%= f.input :shipping_address  %>
          </div>

        <div class="checkout">
          <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
   <br>
   <br>
    <%= link_to("Delete All", clean_carts_path ,
              method: :delete , class: "btn btn-default pull-right",
              style: "text-decoration: underline;",
              data: { confirm: "Are you sure？"} )%>

    <h2> Shopping Basket </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Title</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Option</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to product_path(cart_item.product) do %>
                <% if cart_item.product.image.present? %>
                  <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              $ <%= cart_item.product.price %>
            </td>
            <td>
              <% cart_item = current_cart.cart_items.find_by(product_id: cart_item.product_id) %>

             <%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
               <%= f.select :quantity, 1..cart_item.product.quantity %>
               <%= f.submit "更新", data: { disable_with: "Submiting..." } %>
             <% end %>
            </td>
            <td>
             <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
               <i class="fa fa-trash"></i>
             <% end %>
           </td>
          </tr>
          </tr>
        <% end %>

      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
         <span> Total <%= render_cart_total_price(current_cart) %> USD  </span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
      <%= link_to("Checkout", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>