config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  namespace :account do
   resources :orders
   resources :appointments do
     member do
       post :apply_to_cancel
     end
   end
 end

  namespace :admin do
    resources :products
    resources :services
    resources :categories
    resources :blogs
    resources :topics
    resources :appointments do
      member do
        post :deal
        post :confirm
        post :cancel
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
    resources :reviews
  end

  resources :services do
    resources :comments
    resources :appointments
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders
  resources :blogs do
    member do
      put "like", to: "blogs#upvote"
      put "dislike", to: "blogs#downvote"
    end
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :booking_name, presence: true
  validates :booking_phone, presence: true
  validates :booking_time, presence:true
  validates :booking_email, presence:true

  def book!
    self.update_columns(is_booked: true)
  end


  include AASM
  aasm do
    state :order_placed, initial: true
    state :booked
    state :confirming
    state :confirmed
    state :appointment_cancelled

    event :make_appointment, after_commit: :book! do
      transitions from: :order_placed, to: :booked
    end

    event :deal do
      transitions from: :booked,  to: :confirming
    end

    event :confirm do
      transitions from: :confirming, to: :confirmed
    end

    event :cancel_appointment do
      transitions from: [:booked, :confirming, :confirmed], to: :appointment_cancelled
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

	mount_uploader :image, ImageUploader
	belongs_to :user
	belongs_to :topic
	has_many :messages

	scope :recent, -> { order("created_at DESC")}

  acts_as_votable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
   cart_items.destroy_all
 end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :body, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :blog
	validates :body, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  belongs_to :user

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  has_many :product_lists

  
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :reviews
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :body, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :appointments
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :blogs

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
    is_admin
  end

  has_many :orders
  has_many :comments
  has_many :reviews

  has_many :blogs
  has_many :messages
  
  has_many :appointments

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"
    def index
        @products = Product.all
    end

    def new
        @product = Product.new
        @categories = Category.all.map { |c| [c.name, c.id] }
    end

    def edit
        @product = Product.find(params[:id])
        @categories = Category.all.map { |c| [c.name, c.id] }
    end

    def update
        @product = Product.find(params[:id])
        @product.category_id = params[:category_id]

        if @product.update(product_params)
            redirect_to admin_products_path
        else
            render :edit
        end
    end

    def create
        @product = Product.new(product_params)
        @product.category_id = params[:category_id]

        if @product.save
            redirect_to admin_products_path
        else
            render :new
        end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to admin_products_path, alert: "Product deleted"
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 layout "product"

 def search
  if params[:search].present?
    @products = Product.search(params[:search], fields:["title"])
  else
    @products = Product.all
  end
end

  def index
    if params[:category].blank?
      @products = Product.all.paginate(:page => params[:page], :per_page => 6)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).paginate(:page => params[:page], :per_page => 6)
    end

 end

 def show
   @product = Product.find(params[:id])
 end

 def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
   else
     flash[:warning] = "Your cart has this item"
    end
    redirect_to :back
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h2>
    Edit Product
</h2>

<%= simple_form_for [:admin, @product] do |f| %>

<div class="group">
    <%= f.input :title %>
</div>

<div class="group">
    <%= f.input :description %>
</div>

<div class="group">
    <%= f.input :quantity %>
</div>

<div class="group">
    <%= f.input :price %>
</div>

<% if @product.image.present? %>
<span>目前商品图</span>
<br>
<%= image_tag(@product.image.thumb.url) %>
<% end %>

<div class="group">
    <%= f.input :image, as: :file %>
</div>

<%= f.select :category_id, @categories %>
<br>
<br>

<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2 class="text-center"> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("Add new category", new_admin_category_path,class: "btn btn-default btn-sm") %>
  <%= link_to("Category 清单", admin_categories_path, class: "btn btn-default btn-sm") %>
  <%= link_to("Add new product", new_admin_product_path, class: "btn btn-default btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          $  <%= product.price %>
        </td>
        <td> <%= product.category.name %></td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>|
          <%= link_to("Destroy", admin_product_path(product), method: :delete, data: { :confirm => "Are you sure?"}) %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "类别") %>
  <br>
  <br>
  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/products/index.html.erb
<div class="row">
<% @products.each do |product| %>
<div class="col-sm-4 col-xs-6">
    <span class="thumbnail">
        <%= link_to product_path(product) do %>
        <% if product.image.present? %>
        <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
    <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
        <% end %>
        <h4><%= product.title %></h4>
        <h6>Category: <%= product.category.name %></h6>

        <div class="rating">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
        </div>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        </p>
        <hr class="line">
        <div class="row">
            <div class="col-sm-6">
                <p class="price">
                    $
                    <%= product.price %></p>
            </div>

            <div class="col-sm-6">

                <%= link_to("But Item", product_path(product),  class:"btn btn-info right") %>
            </div>
        </div>
    </span>
</div>


<% end %>
</div>
<div class="row">
  <div class="text-center">
    <%= will_paginate @products %>
  </div>
</div>

app/views/products/search.html.erb
<% @products.each do |product| %>
<div class="col-sm-4 col-xs-6">
    <span class="thumbnail">
        <%= link_to product_path(product) do %>
        <% if product.image.present? %>
        <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
    <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
        <% end %>
        <h4><%= product.title %></h4>
        <h6>Category: <%= product.category.name %></h6>

        <div class="rating">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
        </div>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        </p>
        <hr class="line">
        <div class="row">
            <div class="col-sm-6">
                <p class="price">
                    $
                    <%= product.price %></p>
            </div>

            <div class="col-sm-6">

                <%= link_to("But Item", product_path(product),  class:"btn btn-info right") %>
            </div>
        </div>
    </span>
</div>
<% end %>

app/views/products/show.html.erb
<div class="row">
    <div class="col-sm-6">
        <% if @product.image.present? %>
        <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
        <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
        <% end %>
    </div>
    <div class="col-sm-5 col-md-offset-1">
        <div class="container-fluid">
            <h2>
                <%= @product.title %>
            </h2>

            <p>
                <%= @product.description %>
            </p>

            <div>
                Quantity :
                <%= @product.quantity %>
            </div>
            <div>
                Category :
                <%= @product.category.name %>
            </div>
            <div class="product-price">
                $
                <%= @product.price %>
            </div>
        </div>
        <br>
        <br>
        <div class="pull-right">
            <% if @product.quantity.present? && @product.quantity > 0 %>
            <%= link_to("Add to Basket", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-lg") %>
        <% else %>
            We haven't this item
            <% end %>
        </div>
    </div>
</div>

<div class="row review">
  <div class="col-sm-10 col-sm-offset-1">
    <h3 class="reviews_title">
      <%= @product.reviews.count %> Reviews
    </h3>
    <hr>
    <div id="reivews">
      <%= render @product.reviews%>
      <hr>
      <%= render "reviews/form"%>
    </div>
  </div>
</div>