config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  namespace :account do
   resources :orders
   resources :appointments do
     member do
       post :apply_to_cancel
     end
   end
 end

  namespace :admin do
    resources :products
    resources :services
    resources :categories
    resources :blogs
    resources :topics
    resources :appointments do
      member do
        post :deal
        post :confirm
        post :cancel
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
    collection do
      get :search
    end
    resources :reviews
  end

  resources :services do
    resources :comments
    resources :appointments
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders
  resources :blogs do
    member do
      put "like", to: "blogs#upvote"
      put "dislike", to: "blogs#downvote"
    end
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :booking_name, presence: true
  validates :booking_phone, presence: true
  validates :booking_time, presence:true
  validates :booking_email, presence:true

  def book!
    self.update_columns(is_booked: true)
  end


  include AASM
  aasm do
    state :order_placed, initial: true
    state :booked
    state :confirming
    state :confirmed
    state :appointment_cancelled

    event :make_appointment, after_commit: :book! do
      transitions from: :order_placed, to: :booked
    end

    event :deal do
      transitions from: :booked,  to: :confirming
    end

    event :confirm do
      transitions from: :confirming, to: :confirmed
    end

    event :cancel_appointment do
      transitions from: [:booked, :confirming, :confirmed], to: :appointment_cancelled
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord

	mount_uploader :image, ImageUploader
	belongs_to :user
	belongs_to :topic
	has_many :messages

	scope :recent, -> { order("created_at DESC")}

  acts_as_votable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clean!
   cart_items.destroy_all
 end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :body, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :blog
	validates :body, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token

  def generate_token
    self.token = SecureRandom.uuid
  end

  belongs_to :user

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  has_many :product_lists

  
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :reviews
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :body, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments
  has_many :appointments
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :blogs

	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def admin?
    is_admin
  end

  has_many :orders
  has_many :comments
  has_many :reviews

  has_many :blogs
  has_many :messages
  
  has_many :appointments

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="row" style="margin-top: 50px;">
    <p class="text-center">Copyright ©2017 Pet_Grooming
        <br>Design by <strong>MaoYaoji and FengChi</stron>

    </p>
</footer>

app/views/common/_navbar.html.erb
<div class="row">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><img src='<%= image_url 'logo.png' %>'>Pet-Grooming
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav">
                    <li><%= link_to("Services", services_path) %> </li>
                    <li>
                        <%= link_to("Shop", products_path) %>
                    </li>
                    <li>
                        <%= link_to("Blog", blogs_path)%>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <% if !current_user %>
                    <li>
                        <a href="#" data-toggle="modal" data-target="#signup-modal">SignUp</a>
                    </li>

                    <li>
                        <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                    </li>
                <% else %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi!,
                            <%= current_user.email %>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <% if current_user.admin? %>
                            <li>
                                <%= link_to("Admin 选单", admin_products_path ) %>
                            </li>
                            
                            <% end %>
                            <li>
                                <%= link_to("个人订单列表", account_orders_path ) %>
                            </li>
                            <li><%= link_to("My Appointment", account_appointments_path) %></li>
                            <li>
                                <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %>
                            </li>
                        </ul>
                </ul>
            </li>
            <% end %>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
<div>

<!-- 以下代码为登陆注册弹窗代码 -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog" role="document">
        <div class="loginmodal-container">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h2>Log in</h2>
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-inputs">
                <%= f.input :email, required: false, autofocus: true %>
                <%= f.input :password, required: false %>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
            </div>
            <div class="form-actions">
                <%= f.button :submit, "Log in" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="loginmodal-container">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h2>Sign up</h2>
            <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :email, required: true, autofocus: true %>
                <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                <%= f.input :password_confirmation, required: true %>
            </div>
            <div class="form-actions">
                <%= f.button :submit, "Sign up" %>
            </div>
            <% end %>
        </div>
    </div>
</div>